package com.example.vchatmessengerserver.user;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
// dto class for user creation
public class CreateUserDto {
    // user's name field
    private String name;
    // user's nickname field
    private String nickname;
    // user's password field
    private String password;
    // encoded in base64 format user's avatar
    private String avatarData;
    // type of user's avatar (1 - autogenerated, 2 - loaded from device)
    private int avatarType;
}
